---
name: OSSAR # https://github.com/github/ossar-action

on:
  push:
  pull_request:

jobs:
  OSSAR-Scan:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Install
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: '3.1.201'

      - run: mkdir D:\a_msca\versions\temp

      - name: Checkout nodeJS
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14

      - run: |
          npm i
          npm run build

      - name: Run OSSAR
        uses: github/ossar-action@v1
        id: ossar

      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
